<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/01_wprowadzenie/wprowadzenie01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print('hello colab')

hello colab


Numpy

In [4]:
import numpy as np
np.__version__


'2.0.2'

In [5]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1D array

In [7]:
x = np.array([1,3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
 x = np.array([1.3, 2.3, 1.4])
 print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Arrays



In [15]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [19]:
x.shape

(2, 3)

3D Arrays

In [20]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

     [[4,1,3],
      [3,2,1]],


     [[3,2,1],
      [4,3,1]]]


)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [3, 2, 1]],

       [[3, 2, 1],
        [4, 3, 1]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(3, 2, 3)

Typy danych

In [23]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
A = np.array([1.0,2.3,3.23])
A.dtype

dtype('float64')

In [25]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [26]:
A

array([1., 2., 3.])

In [27]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [28]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A = np.array([1.0,2.7,3.23], dtype='int')
A.dtype

dtype('int64')

In [30]:
A


array([1, 2, 3])

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [32]:
A = np.array([24, 120, 230], dtype = np.int16)
A.dtype

dtype('int16')

In [33]:
A = np.array([24, 120, 230], dtype = np.uint16)
A.dtype

dtype('uint16')

Tworzenie tablic

In [34]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [42]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [43]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [44]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [45]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [53]:
 A = np.array([3,1,4,2])
 B = np.array([3,-1,3,2])
 print(A)
 print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [54]:
A + B


array([6, 0, 7, 4])

In [56]:
A - B

array([0, 2, 1, 0])

In [57]:
A * B

array([ 9, -1, 12,  4])

In [58]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [59]:
 A + 3

array([6, 4, 7, 5])

In [60]:
2 * A

array([6, 2, 8, 4])

In [61]:
A + 3*B

array([12, -2, 13,  8])

In [62]:
np.add(A,B)

array([6, 0, 7, 4])

In [63]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [64]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [65]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [66]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [67]:
X * Y

array([[6, 0],
       [2, 0]])

In [68]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [69]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [70]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [71]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudo losowych


In [72]:
np.random.seed(0)

In [73]:
np.random.randn()

1.764052345967664

In [74]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [75]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [76]:
np.random.rand()

0.1965823616800535

In [77]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [78]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [79]:
np.random.randint(10)

3

In [81]:
np.random.randint(low=10, high=101)

56

In [82]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [89]:
np.random.choice([4,2,1,4, 5])

np.int64(5)

In [90]:
np.random.choice(['python', 'java', 'sql'])

np.str_('python')

In [93]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.random.shuffle(data)
data

array([1, 8, 2, 3, 6, 5, 7, 0, 9, 4])

Podstawowe funkcje

In [96]:
np.exp(1)

np.float64(2.718281828459045)

In [97]:
np.sqrt(9)

np.float64(3.0)

In [98]:
np.all([2,3,1])

np.True_

In [99]:
np.any([0,0,0])

np.False_

In [101]:
bool(1.2)

True

In [104]:
A = np.random.rand(5)
A

array([0.4287687 , 0.13547406, 0.29828233, 0.56996491, 0.59087276])

In [105]:
np.argmax(A)

np.int64(4)

In [106]:
A[np.argmax(A)]

np.float64(0.5908727612481732)

In [107]:
np.argmin(A)

np.int64(1)

In [108]:
np.argsort(A)

array([1, 2, 0, 3, 4])

In [109]:
np.max(A)

np.float64(0.5908727612481732)

In [110]:
np.min(A)

np.float64(0.13547406422245023)

In [111]:
# Srednia
np.mean(A)

np.float64(0.40467255261473706)

In [112]:
np.median(A)

np.float64(0.42876870094576613)

In [113]:
#odchylenie standardowe
np.std(A)

np.float64(0.17109027569240406)

Indeksowanie wycinanie

In [115]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [116]:
# A[idx], A[start:stop], A[:stop], A[start:]
A[2]

np.int64(2)

In [117]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [118]:
A[:2]

array([0, 1])

In [119]:
A[[0,2]]

array([0, 2])

In [120]:
A[-1]

np.int64(19)

In [121]:
A[10:15]

array([10, 11, 12, 13, 14])

In [122]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [124]:
A[1]

array([5, 6, 7, 8, 9])

In [126]:
# zwracanie kolumn
A[:,0]

array([ 0,  5, 10, 15])

In [127]:
# konkretny indeks

A[1,1]

np.int64(6)

In [128]:
A[1,3]

np.int64(8)

In [129]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [132]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

iteracja po tablicach


In [133]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [135]:
for row in A:
  print(row[0])

0
5
10
15


In [136]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [137]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


zmiana rozmiaru

In [138]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
A.shape

(4, 5)

In [140]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [142]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [143]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [145]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [146]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [148]:
#wartosci pomiedzy
np.bitwise_and(A> -5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [149]:
A[np.bitwise_and(A> -5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [150]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])